fun main(args: Array<String>) {
    val chocolates= ArrayList<Chocolate>()
    val chocolate1= Chocolate("Hershey")
    val chocolate2= Chocolate("Twix")
    val chocolate3= Chocolate("Milky Way")
    val chocolate4= Chocolate("M&M")
    chocolates.add(chocolate1)
    chocolates.add(chocolate2)
    chocolates.add(chocolate3)
    chocolates.add(chocolate4)
    val boxOfChocolate= BoxOfThings<Chocolate>(chocolates)
    val forestGump= ForrestGump(boxOfChocolate)
    println(forestGump.pickChocolate())
    println(forestGump.pickChocolate())
    println(forestGump.pickChocolate())
    println(forestGump.pickChocolate())
    println(forestGump.pickChocolate())
    println(forestGump.pickChocolate())
}